export enum DefaulStatus {
    PENDING = 'Pending',
    ACTIVE = 'Active',
    ACCEPTED = 'Accepted',
    CANCELLED = 'Cancelled',
  }

export enum ProfitCenterStatus {
  STATUS_PROFIT_CTR_INACTIVE_CREATE = 'INACTIVE_CREATE',
  STATUS_PROFIT_CTR_INACTIVE_UPDATE = 'INACTIVE_UPDATE',
  STATUS_PROFIT_CTR_INACTIVE_DELETE = 'INACTIVE_DELETE',
  STATUS_PROFIT_CTR_ACTIVE_CREATE = 'ACTIVE_CREATE',
  STATUS_PROFIT_CTR_ACTIVE_UPDATE = 'ACTIVE_UPDATE',
  STATUS_PROFIT_CTR_ACTIVE_DELETE = 'ACTIVE_DELETE',
}

export enum CostCenterStatus {
  STATUS_COST_CTR_INACTIVE_CREATE = 'INACTIVE_CREATE',
  STATUS_COST_CTR_INACTIVE_UPDATE = 'INACTIVE_UPDATE',
  STATUS_COST_CTR_INACTIVE_DELETE = 'INACTIVE_DELETE',
  STATUS_COST_CTR_ACTIVE_CREATE = 'ACTIVE_CREATE',
  STATUS_COST_CTR_ACTIVE_UPDATE = 'ACTIVE_UPDATE',
  STATUS_COST_CTR_ACTIVE_DELETE = 'ACTIVE_DELETE',
}