import { getDb } from '../migrations-utils/db';

export const up = async () => {
  const db = await getDb();

  // Insert data into 'sl' collection
  const slData = [
    { code: 1009, name: 'REVOLVING FUND-TRIP' },
    { code: 1010, name: 'PETTYCASH-LOCAL PURCHASES' },
    { code: 1011, name: 'EMERGENCY FUND C/O TANG BOY' },
    { code: 1012, name: 'PCF-COMMON' },
    { code: 1013, name: 'C/O CUBAO' },
    { code: 1014, name: 'C/O STK' },
    { code: 1015, name: 'LPP PCF C/O JOY ZALDIVAR' },
    { code: 1016, name: 'MBTC - P.TUAZON CA# 3013-50858-6' },
    { code: 1017, name: 'MBTC - SFD CA# 3069-50105-3' },
    { code: 1018, name: 'BDO CUBAO CA# 282-0064-627' },
    { code: 1019, name: 'BDO SA#00282-0216699 CUBAO (LPP ACCOUNT)' },
    { code: 1020, name: 'BDO SA#00282-0206-286 CUBAO ACC LOCAL' },
    { code: 1021, name: 'BDO CUBAO CA# 282-0064-627' },
    { code: 1022, name: 'EUROMARKET DESIGNS' },
    { code: 1023, name: 'ANTHROPOLOGIE' },
    { code: 1024, name: 'WILLIAM SONOMA INC.' },
    { code: 1025, name: 'NATURAL LIGHT' },
    { code: 1026, name: 'CURREY INTERNATIONAL ' },
    { code: 1027, name: 'SAIKA CO., LTD' },
    { code: 1028, name: 'HAVE YOU MET MISS JONES' },
    { code: 1029, name: 'PACIFIC LIFESTYLE' },
    { code: 1030, name: 'STEINHOFF' },
    { code: 1031, name: 'HOUSE DOCTOR' },
    { code: 1032, name: 'ARTERIORS HOME' },
    { code: 1033, name: 'HK LIVING BV' },
    { code: 1034, name: 'TROY LIGHTING' },
    { code: 1035, name: 'QUOROM (BRIDGEBLUE)' },
    { code: 1036, name: 'DUSTY' },
    { code: 1037, name: 'MAKERS PALM' },
    { code: 1038, name: 'La Forge Designs' },
    { code: 1039, name: 'PORT TO PORT IMPORT/EXPORT INC' },
    { code: 1040, name: 'TARGET LIGHTING' },
    { code: 1041, name: 'VIPS AND FRIENDS' },
    { code: 1042, name: 'YAYA, NL' },
    { code: 1043, name: 'HOMEGOODS' },
    { code: 1044, name: 'WEYLANDS' },
    { code: 1045, name: 'A/R OTHERS' },
    { code: 1046, name: 'ALBERTO JOVEN' },
    { code: 1047, name: 'ROEL GOMEZ' },
    { code: 1048, name: 'MAYRA MANGIO' },
    { code: 1049, name: 'LLOYD CANLAS' },
    { code: 1050, name: 'RONALD R. BARLAM' },
    { code: 1051, name: 'OTHER SUPPLIERS / SUB-CON' },
    { code: 1052, name: 'COMPANY LOAN' },
    { code: 1053, name: "	K'S - APEC LENDING	" },
    { code: 1054, name: 'MTK' },
    { code: 1055, name: 'WCK' },
    { code: 1056, name: 'AKP' },
    { code: 1057, name: 'CHRISTINE GAY MALOOM' },
    { code: 1058, name: 'MAVIC MENDINA' },
    { code: 1059, name: 'BENGCO, CRISANTO' },
    { code: 1060, name: 'OTHER' },
    { code: 1061, name: 'ROMELLA ABULAR' },
    { code: 1062, name: 'ALVIN LANO' },
    { code: 1063, name: 'RAFAEL MONGE' },
    { code: 1064, name: 'ALEXANDER YABUT' },
    { code: 1065, name: 'ANGELIE TIGLAO' },
    { code: 1066, name: 'CJ CASTRO' },
    { code: 1067, name: 'ALVIN CAMIGLA' },
    { code: 1068, name: "	K'S KABIGTING	" },
    { code: 1069, name: 'ROBERTO S. LUMBA' },
    { code: 1070, name: 'JOMAR' },
    { code: 1071, name: 'VICTOR RESSURECTION' },
    { code: 1072, name: 'MARIA ARACELI CALIMOT' },
    { code: 1073, name: 'OTHERS' },
    { code: 1074, name: 'LLOYD CANLAS' },
    { code: 1075, name: 'A/R OTHERS' },
    { code: 1076, name: 'LLOYD CANLAS' },
    { code: 1077, name: 'SCIENTIFIC STANDARD SERVICES INC.' },
    { code: 1078, name: "	METALS INDUSTRY RESARCH & DEV'T CENTER	" },
    { code: 1079, name: 'SHINE TEAM GLOBAL CORP.' },
    { code: 1080, name: 'LONGWIN LIGTHTING CO.,LIMITED' },
    { code: 1081, name: 'RHJ LIGHTING LIMITED' },
    { code: 1082, name: 'QUANZHOU XUYANG LIGHTING CO., LTD' },
    { code: 1083, name: 'DONGGUAN TAIJIHENG PRECISION TECHNOLOGY' },
    { code: 1084, name: 'JERIC V. PINEDA' },
    { code: 1085, name: 'FIL-AMERICAN HARDWARE CO.' },
    { code: 1086, name: 'MOLDEX' },
    { code: 1087, name: 'GARBES DIZON & SON INC.' },
    { code: 1088, name: 'TARGET LIGHTING' },
    { code: 1089, name: 'VICTOR RESSURECCION' },
    { code: 1090, name: 'JERIC V, PINEDA' },
    { code: 1091, name: 'DELSAN OFFICE SYSTEMS' },
    { code: 1092, name: 'XINGYASHI PACKAGING PRODUCTS' },
    { code: 1093, name: 'OTHERS' },
    { code: 1094, name: 'SALARIES & WAGES-PRM/ON CALL' },
    { code: 1095, name: 'SALARIES & WAGES-TS' },
    { code: 1096, name: 'OVERTIME & NIGHT DIFF-PRM/ON CALL' },
    { code: 1097, name: 'PREMIUM PAY-ON CALL/PRM' },
    { code: 1098, name: '13TH MONTH PAY' },
    { code: 1099, name: 'SSS/PHIC/HDMF CONTRI(EXE DRIVER)' },
    { code: 1100, name: 'PERSONNEL TRAINING AND RECRUITMENT' },
    { code: 1101, name: 'COMMUNICATION EXPENSE' },
    { code: 1102, name: 'TRANSPORTATION & TRAVEL' },
    { code: 1103, name: 'FUEL, OIL & LUBRICANTS' },
    { code: 1104, name: 'COMPUTER SOFTWARE MAINT.' },
    { code: 1105, name: 'STATIONERIES & OFFICE SUPPL.' },
    { code: 1106, name: 'PLANT SUPPLIES' },
    { code: 1107, name: 'BANK CHARGES' },
    { code: 1108, name: 'TAXES AND LICENSES' },
    { code: 1109, name: 'PROFESSIONAL FEE' },
    { code: 1110, name: 'MEALS & SNACKS' },
    { code: 1111, name: 'ADVERTISING & PUBLICATION' },
    { code: 1112, name: 'ALL ATTACHED TO SAMPLES' },
    { code: 1113, name: 'TRUCKING COSTS' },
    { code: 1114, name: 'MISCELLANEOUS EXPENSES' },
    { code: 1115, name: 'NOTARY FEE' },
    { code: 1116, name: 'TRADE & FAIR SUPPLIES' },
    { code: 1117, name: 'PRD-THERMIC AND FIRING COST' },
    { code: 1118, name: 'CASH IN BANK' },
    { code: 1119, name: 'TRADE FAIR' },
    { code: 1120, name: 'FUEL, OIL & LUBRICANTS' },
    { code: 1121, name: 'TAXES AND LICENSES' },
    { code: 1122, name: 'PROFESSIONAL FEE' },
    { code: 1123, name: 'BPI CAPITOL' },
    { code: 1124, name: "	BDO INVESTMENT (K'S)	" },
    { code: 1125, name: 'MBTC SFDO TD' },
    { code: 1126, name: 'CLAY' },
    { code: 1127, name: 'PAINTS' },
    { code: 1128, name: 'ATTACHMENT & PRODUCTION SUPPLIES' },
    { code: 1129, name: 'PACKAGING & LABELLING' },
    { code: 1130, name: 'LPG' },
    { code: 1131, name: 'GLAZING MATERIALS' },
    { code: 1132, name: 'WOOD' },
    { code: 1133, name: 'COMPANY LOAN' },
    { code: 1134, name: 'SICKNESS BENEFIT' },
    { code: 1135, name: "	K'S - APEC LENDING	" },
    { code: 1136, name: 'TAX PAYABLE-EMPLOYEE' },
    { code: 1137, name: 'LEOMEL NUQUI' },
    { code: 1138, name: 'CALMA, ORNIDA' },
    { code: 1139, name: 'EXCESS USAGE-PLAN BENEFIT' },
    { code: 1140, name: 'CHRISTINE GAY MALOOM' },
    { code: 1141, name: 'THEZ R. CAMINS' },
    { code: 1142, name: 'DIMATULAC, CLAUDINE' },
    { code: 1143, name: 'BENGCO, CRISANTO' },
    { code: 1144, name: 'SANTOS, JOEL' },
    { code: 1145, name: 'OTHER' },
    { code: 1146, name: 'HENRY BARTOLOME' },
    { code: 1147, name: 'ALVIN LANO' },
    { code: 1148, name: 'MANARPAAC,CHRISTINE' },
    { code: 1149, name: 'ROWELL CACDAC' },
    { code: 1150, name: 'CELYN/VERIFIED BY PAYEE' },
    { code: 1151, name: 'CELYN/NOT VERIFIED/MISSING VOUCHERS' },
    { code: 1152, name: 'ALVIN CAMIGLA' },
    { code: 1153, name: "	K'S KABIGTING	" },
    { code: 1154, name: 'RETROFITTING OF B2-2ND FLOOR' },
    { code: 1155, name: 'JERIC PINEDA PROPERTY' },
    { code: 1156, name: 'CUBAO CONSTRUCTION' },
    { code: 1157, name: 'DIGITIZATION PROJECT' },
    { code: 1158, name: 'packed goods warehouse' },
    { code: 1159, name: 'PM -PAYLOADER' },
    { code: 1160, name: 'FEEDMILL -SLAB FORMING AREA' },
    { code: 1161, name: 'WOODKILN 1' },
    { code: 1162, name: 'SLAB FORMING DRYING AND PATHWAY' },
    { code: 1163, name: 'Roofing Project 2024 (BLDG 1 ,2 & 3)' },
    { code: 1164, name: 'THROWING PALLETS' },
    { code: 1165, name: 'PACKING-CONRETING OF WALLS' },
    { code: 1166, name: 'GUARDHOUSE PROJECT' },
    { code: 1167, name: 'FACTORY EXPANSION' },
    { code: 1168, name: 'STORAGE AREA AND DISMANTLING OF DRYER' },
    { code: 1169, name: 'CASTING EXPANSION PROJECT' },
    { code: 1170, name: 'SALARIES & WAGES-TS' },
    { code: 1171, name: 'PERSONNEL TRAINING AND RECRUITMENT' },
    { code: 1172, name: 'COMMUNICATION EXPENSE' },
    { code: 1173, name: 'TRANSPORTATION & TRAVEL' },
    { code: 1174, name: 'FUEL, OIL & LUBRICANTS' },
    { code: 1175, name: 'COMPUTER SOFTWARE MAINT.' },
    { code: 1176, name: 'STATIONERIES & OFFICE SUPPL.' },
    { code: 1177, name: 'PLANT SUPPLIES' },
    { code: 1178, name: 'TAXES AND LICENSES' },
    { code: 1179, name: 'INSURANCE EXPENSE' },
    { code: 1180, name: 'SECURITY SERVICES' },
    { code: 1181, name: 'RENT EXPENSE' },
    { code: 1182, name: 'DONATIONS & CONTRIBUTION' },
    { code: 1183, name: 'ASSOCIATION DUES' },
    { code: 1184, name: 'PRODUCT TESTING & ANALYSIS' },
    { code: 1185, name: "	BUYER'S AUDIT	" },
    { code: 1186, name: 'EMPLOYEE BENEFITS' },
    { code: 1187, name: 'R & M-- ROLLER KNEADER' },
    { code: 1188, name: 'R & M-- EXTRUDER' },
    { code: 1189, name: 'R & M -- STRADA ZHG877' },
    { code: 1190, name: 'SPARE MATERIALS' },
    { code: 1191, name: 'BKK TRIP' },
    { code: 1192, name: 'R & M -- FILTER PRESS#2' },
    { code: 1193, name: 'AMBIENTE 2023' },
    { code: 1194, name: 'JCP PARIS' },
    { code: 1195, name: 'CASTING TRAINING' },
    { code: 1196, name: 'PM-EXTRUDER' },
    { code: 1197, name: 'MOLD MAKING TRAINING' },
    { code: 1198, name: 'AMBIENTE 2024' },
    { code: 1199, name: 'US OCTOBER TRIP-High point market' },
    { code: 1200, name: 'PMS SCREW TYPE COMPRESSOR' },
    { code: 1201, name: 'OCTOBER SHOW 2023-MANILA FAME' },
    { code: 1202, name: 'THERMIC DRYER 1' },
    { code: 1203, name: 'AMBIENTE 2025' },
    { code: 1204, name: 'CONTRIBUTION' },
    { code: 1205, name: 'SSS CONTRIBUTION' },
    { code: 1206, name: 'PHIC CONTRIBUTION' },
    { code: 1207, name: 'HDMF CONTRIBUTION' },
    { code: 1208, name: 'WTAX-COMPENSATION' },
    { code: 1209, name: 'WTAX-EXPANDED' },
    { code: 1210, name: 'TAX REFUND' },
    { code: 1211, name: 'WTAX-EXPANDED- 1%' },
    { code: 1212, name: 'WTAX-EXPANDED- 2%' },
    { code: 1213, name: 'WTAX-EXPANDED- 5%' },
    { code: 1214, name: 'WTAX-EXPANDED- 15%' },
    { code: 1215, name: 'WTAX-COMPENSATION' },
    { code: 1216, name: 'CONTRIBUTION' },
    { code: 1217, name: 'SALARY LOAN' },
    { code: 1218, name: 'CALAMITY LOAN' },
    { code: 1219, name: 'CONTRIBUTION' },
    { code: 1220, name: 'CONTRIBUTION' },
    { code: 1221, name: 'SALARY LOAN' },
    { code: 1222, name: 'CALAMITY LOAN' },
    { code: 1223, name: 'SALARIES & WAGES-PRM/ON CALL' },
    { code: 1224, name: 'SL/VL' },
    { code: 1225, name: '13TH MONTH PAY' },
    { code: 1226, name: 'LAST PAY' },
    { code: 1227, name: 'COMMISSION' },
    { code: 1228, name: 'PERSONNEL TRAINING AND RECRUITMENT' },
    { code: 1229, name: 'PROFESSIONAL FEE' },
    { code: 1230, name: 'EMPLOYEE BENEFITS' },
    { code: 1231, name: 'CORPORATE ACTIVITIES' },
    { code: 1232, name: "	BUYER'S CHARGE BACK	" },
    { code: 1233, name: 'BONUS' },
    { code: 1234, name: 'UNRELEASED CHECKS' },
    { code: 1235, name: 'TAX REFUND' },
    { code: 1236, name: 'KABIGTING-A/R ELIZA' },
    { code: 1237, name: 'UN-IDENTIFIED DEPOSIT' },
    { code: 1238, name: 'OTHERS' },
    { code: 1239, name: 'EUROMARKET DESIGNS' },
    { code: 1240, name: 'ANTHROPOLOGIE' },
    { code: 1241, name: 'WILLIAM SONOMA INC.' },
    { code: 1242, name: 'CURREY INTERNATIONAL' },
    { code: 1243, name: 'SAIKA CO., LTD' },
    { code: 1244, name: 'HAVE YOU MET MISS JONES' },
    { code: 1245, name: 'PACIFIC LIFESTYLE' },
    { code: 1246, name: 'STEINHOFF' },
    { code: 1247, name: 'HOUSE DOCTOR' },
    { code: 1248, name: 'ARTERIORS HOME' },
    { code: 1249, name: 'HK LIVING BV' },
    { code: 1250, name: 'TROY LIGHTING' },
    { code: 1251, name: 'DUSTY' },
    { code: 1252, name: 'MAKERS PALM' },
    { code: 1253, name: 'PORT TO PORT IMPORT/EXPORT INC' },
    { code: 1254, name: 'TARGET LIGHTING' },
    { code: 1255, name: 'VIPS AND FRIENDS' },
    { code: 1256, name: 'YAYA, NL' },
    { code: 1257, name: 'HOMEGOODS' },
    { code: 1258, name: 'WEYLANDS' },
    { code: 1259, name: 'REALIZED' },
    { code: 1260, name: 'UNREALIZED' },
    { code: 1261, name: 'CLAY' },
    { code: 1262, name: 'PAINTS' },
    { code: 1263, name: 'ATTACHMENT & PRODUCTION SUPPLIES' },
    { code: 1264, name: 'PACKAGING & LABELLING' },
    { code: 1265, name: 'LPG' },
    { code: 1266, name: 'GLAZING MATERIALS' },
    { code: 1267, name: 'SEMI-FINISHED GOODS/WORK IN PROCESS' },
    { code: 1268, name: 'ATTACHMENT' },
    { code: 1269, name: 'PRODUCTION SUPPLIES' },
    { code: 1270, name: 'ATTACHMENT MATERIALS' },
    { code: 1271, name: 'WOOD' },
    { code: 1272, name: 'ATTACHMENT - ELECTRICALS' },
    { code: 1273, name: 'INDIRECT MATERIALS' },
    { code: 1274, name: 'FREIGHT COSTS-DM' },
    { code: 1275, name: 'FREIGHT COSTS-ELECTRICAL' },
    { code: 1276, name: 'DM - MISC' },
    { code: 1277, name: 'REPAIRS & MAINTENANCE' },
    { code: 1278, name: 'R & M -- LAPTOP' },
    { code: 1279, name: 'R & M PRINTER' },
    { code: 1280, name: 'R & M -- TOYOTA FORTUNER NCL 3156/A3G796' },
    { code: 1281, name: 'STAFF HOUSE' },
    { code: 1282, name: 'R & M -- T.FX UPW310' },
    { code: 1283, name: 'R & M -- HIACE WLH742' },
    { code: 1284, name: 'R & M -- N.TRUCK WDX554' },
    { code: 1285, name: 'R & M -- GRANDIA UQB 351' },
    { code: 1286, name: 'R & M -- FUSO CAB5511/MITSUBISHI B1G974' },
    { code: 1287, name: 'R & M-- AIR COMPRESSOR' },
    { code: 1288, name: 'R & M-- KILN' },
    { code: 1289, name: 'R & M-- FORKLIFT' },
    { code: 1290, name: 'R & M-- BUILDING' },
    { code: 1291, name: 'R & M-- FILTER PRESS' },
    { code: 1292, name: 'R & M-- ROLLER KNEADER' },
    { code: 1293, name: 'R & M-- PAYLOADER' },
    { code: 1294, name: 'R & M-- PUGMILL' },
    { code: 1295, name: 'R & M-- EXTRUDER' },
    { code: 1296, name: 'R & M -- STRADA ZHG877' },
    { code: 1297, name: 'R&M- AGITATING TANK' },
    { code: 1298, name: 'R & M-- VIBRATING SCREEN MACHINE' },
    { code: 1299, name: 'R & M ------- SHOWROOM' },
    { code: 1300, name: 'R & M - SUBARU P# NDY4191 (CS-HW5991)' },
    { code: 1301, name: 'R & M-- BALLMILL' },
    { code: 1302, name: 'R&M SPRAY GUN' },
    { code: 1303, name: 'R & M --- HG/FG SPRAYBOOTH' },
    { code: 1304, name: 'R&M GENSET' },
    { code: 1305, name: 'R & M - MONTERO NM8527/ NAC5583' },
    { code: 1306, name: 'R & M - TEST KILN 2' },
    { code: 1307, name: 'R&M---AIRCON' },
    { code: 1308, name: 'R & M THROWING MACHINE' },
    { code: 1309, name: 'R&M THERMOHYGROMETER' },
    { code: 1310, name: 'CASTING AREA' },
    { code: 1311, name: 'R & M - CLAY PREP' },
    { code: 1312, name: 'R & M - PAJERO CRW 949' },
    { code: 1313, name: 'R&M JETMATIC' },
    { code: 1314, name: 'R&M---CISTERN TANK' },
    { code: 1315, name: 'R & M -- CCTV-SURVEILANCE SYTEM' },
    { code: 1316, name: 'R & M -- SCREW TYPE COMPRESSOR' },
    { code: 1317, name: 'SLAB FORMING MACHINE' },
    { code: 1318, name: 'PM FILTER PRESS#3' },
    { code: 1319, name: 'R & M -- FILTER PRESS#4' },
    { code: 1320, name: 'R & M -- FILTER PRESS#2' },
    { code: 1321, name: 'CALIBRATION OHAUS PRECISION BALANCE' },
    { code: 1322, name: 'R& M-CALIBRATION-DIGITAK/VERNIER CALIPER' },
    { code: 1323, name: 'PM-KILN 1' },
    { code: 1324, name: 'R & M-KILN 3' },
    { code: 1325, name: 'KNEADER PT#1' },
    { code: 1326, name: 'PT KNEADER#2' },
    { code: 1327, name: 'FILTER PRESS#3' },
    { code: 1328, name: 'R & M-VERTICAL PUMP' },
    { code: 1329, name: 'PM-FORKLIFT' },
    { code: 1330, name: 'CALIBRATION-GWINSTEK HI-POT' },
    { code: 1331, name: 'R & M-FILTER PRESS#3' },
    { code: 1332, name: 'PMS SCREW TYPE COMPRESSOR' },
    { code: 1333, name: 'R & M-XENIX' },
    { code: 1334, name: 'THERMIC DRYER 1' },
    { code: 1335, name: 'R & M-AAZ 1968' },
    { code: 1336, name: 'TMX -886 WCI' },
    { code: 1337, name: 'GENSET 1' },
    { code: 1338, name: 'KILN 3' },
    { code: 1339, name: 'R & M - DIAPHRAGM PUMP' },
    { code: 1340, name: 'R & M - HILUX NAC5649' },
    { code: 1341, name: 'STAFFHOUSE' },
    { code: 1342, name: 'INSTALLATION OF GROG MACHINE' },
    { code: 1343, name: ' SALARIES & WAGES-BASIC ' },
    { code: 1344, name: ' SALARIES & WAGES-PRM/ON CALL ' },
    { code: 1345, name: ' SALARIES & WAGES-TS ' },
    { code: 1346, name: ' OVERTIME & NIGHT DIFF-BASIC ' },
    { code: 1347, name: ' OVERTIME & NIGHT DIFF-PRM/ON CALL ' },
    { code: 1348, name: ' PREMIUM PAY-BASIC ' },
    { code: 1349, name: ' PREMIUM PAY-ON CALL/PRM ' },
    { code: 1350, name: ' SL/VL ' },
    { code: 1351, name: ' 13TH MONTH PAY ' },
    { code: 1352, name: ' INCENTIVE PAY ' },
    { code: 1353, name: ' SSS/PHIC/HDMF CONTRI(EXE DRIVER) ' },
    { code: 1354, name: ' SSS AND EC CONTRIBUTION ' },
    { code: 1355, name: ' PHILHEALTH CONTRIBUTIONS ' },
    { code: 1356, name: ' PAG-IBIG FUND CONTRIBUTIONS ' },
    { code: 1357, name: ' DL-SUBCON ' },
    { code: 1358, name: ' COMMISSION ' },
    { code: 1359, name: ' PERSONNEL TRAINING AND RECRUITMENT ' },
    { code: 1360, name: ' COMMUNICATION EXPENSE ' },
    { code: 1361, name: ' TRANSPORTATION & TRAVEL ' },
    { code: 1362, name: ' FUEL, OIL & LUBRICANTS ' },
    { code: 1363, name: ' COMPUTER SOFTWARE MAINT. ' },
    { code: 1364, name: ' STATIONERIES & OFFICE SUPPL. ' },
    { code: 1365, name: ' PLANT SUPPLIES ' },
    { code: 1366, name: ' BANK CHARGES ' },
    { code: 1367, name: ' TAXES AND LICENSES ' },
    { code: 1368, name: ' INSURANCE EXPENSE ' },
    { code: 1369, name: ' SECURITY SERVICES ' },
    { code: 1370, name: ' PROFESSIONAL FEE ' },
    { code: 1371, name: ' RENT EXPENSE ' },
    { code: 1372, name: ' DEPRECIATION EXPENSE ' },
    { code: 1373, name: ' LIGHT and WATER ' },
    { code: 1374, name: ' MEALS & SNACKS ' },
    { code: 1375, name: ' REPRESENTATION & ENTERT. ' },
    { code: 1376, name: ' DONATIONS & CONTRIBUTION ' },
    { code: 1377, name: ' PATERNITY LEAVE ' },
    { code: 1378, name: ' ASSOCIATION DUES ' },
    { code: 1379, name: ' BOOKS & PERIODICALS ' },
    { code: 1380, name: ' BROKERAGE & FORWARDING ' },
    { code: 1381, name: 'REFERRAL FEE' },
    { code: 1382, name: ' FUMIGATION ' },
    { code: 1383, name: ' ALL ATTACHED TO SAMPLES ' },
    { code: 1384, name: ' PRODUCT TESTING & ANALYSIS ' },
    { code: 1385, name: ' MAINTENANCE SUPPLIES ' },
    { code: 1386, name: ' PROMOTIONAL ALLOWANCE ' },
    { code: 1387, name: ' TRUCKING COSTS ' },
    { code: 1388, name: ' COLLECTION CHARGES ' },
    { code: 1389, name: ' PRODUCTS PHOTOSHOOT ' },
    { code: 1390, name: ' TESTING AND ANALYSIS ' },
    { code: 1391, name: ' MATERNITY BENEFITS ' },
    { code: 1392, name: ' DE MINIMIS BENEFIT ' },
    { code: 1393, name: ' MISCELLANEOUS EXPENSES ' },
    { code: 1394, name: ' PARTICIPATION FEE ' },
    { code: 1395, name: ' NOTARY FEE ' },
    { code: 1396, name: ' TCS MATERIALS CONSUMPTION ' },
    { code: 1397, name: ' RETIREMENT PAY ' },
    { code: 1398, name: ' PRD-THERMIC AND FIRING COST ' },
    { code: 1399, name: ' WASTE DISPOSAL ' },
    { code: 1400, name: ' STAFF HOUSE ' },
    { code: 1401, name: ' PENALTY AND OTHER ADDITIONAL CHARGES ' },
    { code: 1402, name: "	 BUYER'S AUDIT 	" },
    { code: 1403, name: ' PEST CONTROL SERVICE ' },
    { code: 1404, name: ' FREIGHT COSTS OF SAMPLE ' },
    { code: 1405, name: ' EMPLOYEE BENEFITS ' },
    { code: 1406, name: ' PROCESSING FEE ' },
    { code: 1407, name: ' CORPORATE ACTIVITIES ' },
    { code: 1408, name: "	 BUYER'S CHARGEBACK 	" },
    { code: 1409, name: ' BONUS ' },
    { code: 1410, name: ' INTERNSHIP ALLOWANCE ' },
    { code: 1411, name: ' BKK TRIP ' },
    { code: 1412, name: ' US TRIP ' },
    { code: 1413, name: ' CB2 INDONESIA TRIP ' },
    { code: 1414, name: ' AMBIENTE 2023 ' },
    { code: 1415, name: ' JCP PARIS ' },
    { code: 1416, name: ' ALLOWANCE ' },
    { code: 1417, name: ' WORLD MARKET PRESENTATION ' },
    { code: 1418, name: ' US OCTOBER TRIP-High point market ' },
    { code: 1419, name: ' AMBIENTE 2024 ' },
    { code: 1420, name: ' OCTOBER SHOW 2023-MANILA FAME ' },
    { code: 1421, name: ' HOUSEKEEPING MATERIALS ' },
    { code: 1422, name: ' LOCAL CHARGES & FORWARDING ' },
    { code: 1423, name: 'VARIOUS MATERIALS' },
    { code: 1424, name: ' TRIP EXPENSE ' },
  ];

  // Get the collection
  const slCollection = db.collection('slcode');

  // Loop through each entry in slData and insert if the code doesn't already exist
  for (const data of slData) {
    const existingDoc = await slCollection.findOne({ code: data.code });

    if (existingDoc) {
      console.log(`Document with code ${data.code} already exists, skipping.`);
    } else {
      // Insert the new document if code doesn't exist
      await slCollection.insertOne(data);
      console.log(`Document with code ${data.code} inserted successfully.`);
    }
  }

  console.log("Data inserted into 'slcode' collection successfully.");
};

export const down = async () => {
  const db = await getDb();
  /*
      Code you downgrade script here!
   */
};
